/**
 * InstantChat Enhanced Color Theme - Modern, accessible, and visually appealing
 */

export const Colors = {
  light: {
    text: '#1a1a1a',
    background: '#ffffff',
    tint: '#2f95dc',
    tabIconDefault: '#ccc',
    tabIconSelected: '#2f95dc',
    primary: '#007AFF',
    primaryLight: '#E3F2FD',
    secondary: '#FF6B35',
    secondaryLight: '#FFF3E0',
    cardBackground: '#f8f9fa',
    cardBackgroundSecondary: '#f1f3f4',
    borderColor: '#e1e5e9',
    borderColorLight: '#f0f0f0',
    myMessage: '#007AFF',
    myMessageText: '#ffffff',
    otherMessage: '#f1f3f4',
    otherMessageText: '#1a1a1a',
    placeholderText: '#8e8e93',
    textSecondary: '#6c757d',
    success: '#34C759',
    successLight: '#E8F5E8',
    warning: '#FF9500',
    warningLight: '#FFF8E1',
    danger: '#FF3B30',
    dangerLight: '#FFEBEE',
  },
  dark: {
    text: '#ffffff',
    background: '#000000',
    tint: '#fff',
    tabIconDefault: '#ccc',
    tabIconSelected: '#fff',
    primary: '#0A84FF',
    primaryLight: '#1C1C1E',
    secondary: '#FF9F0A',
    secondaryLight: '#2C2C2E',
    cardBackground: '#1c1c1e',
    cardBackgroundSecondary: '#2c2c2e',
    borderColor: '#38383a',
    borderColorLight: '#48484a',
    myMessage: '#0A84FF',
    myMessageText: '#ffffff',
    otherMessage: '#2c2c2e',
    otherMessageText: '#ffffff',
    placeholderText: '#8e8e93',
    textSecondary: '#8e8e93',
    success: '#30D158',
    successLight: '#1C1C1E',
    warning: '#FF9F0A',
    warningLight: '#2C2C2E',
    danger: '#FF453A',
    dangerLight: '#1C1C1E',
  },
};

// Additional design tokens
export const DesignTokens = {
  borderRadius: {
    small: 8,
    medium: 12,
    large: 16,
    xlarge: 24,
    round: 50,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  shadows: {
    small: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    medium: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    large: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 8,
    },
  },
  typography: {
    h1: { fontSize: 32, fontWeight: '700' as const, lineHeight: 40 },
    h2: { fontSize: 28, fontWeight: '600' as const, lineHeight: 36 },
    h3: { fontSize: 24, fontWeight: '600' as const, lineHeight: 32 },
    h4: { fontSize: 20, fontWeight: '600' as const, lineHeight: 28 },
    body: { fontSize: 16, fontWeight: '400' as const, lineHeight: 24 },
    bodyBold: { fontSize: 16, fontWeight: '600' as const, lineHeight: 24 },
    caption: { fontSize: 14, fontWeight: '400' as const, lineHeight: 20 },
    captionBold: { fontSize: 14, fontWeight: '600' as const, lineHeight: 20 },
    small: { fontSize: 12, fontWeight: '400' as const, lineHeight: 16 },
  },
};


